@echo off
setlocal enabledelayedexpansion

rem ============================================
rem Configuration des chemins et variables
rem ============================================
set "SCRIPT_DIR=%~dp0"
cd /d "%SCRIPT_DIR%"

rem Configuration Java
set "JAVA_HOME=C:\Program Files\Eclipse Adoptium\jdk-17.0.17+10"
set "PATH=%JAVA_HOME%\bin;%PATH%"
echo [INFO] Using JAVA_HOME=%JAVA_HOME%

rem Configuration SonarCloud
set "SONAR_PROJECT_KEY=Marmelade57_BUT3_QUALDEV_13"
set "SONAR_ORG=marmelade57"
set "SONAR_HOST=https://sonarcloud.io"
if "%SONAR_TOKEN%"=="" (
    set "SONAR_TOKEN=ada0520817d2a5383da445e8922b4af80029b032"
)
echo [INFO] SonarCloud parameters: projectKey=%SONAR_PROJECT_KEY% organization=%SONAR_ORG% host=%SONAR_HOST%

call mvn -version

rem ============================================
rem ÉTAPE 1 : Nettoyage
rem ============================================
echo.
echo [========================================]
echo [ ÉTAPE 1/3 : Nettoyage des anciens rapports ]
echo [========================================]
if exist "target\site\jacoco"      rmdir /s /q "target\site\jacoco"
if exist "target\coverage-reports" rmdir /s /q "target\coverage-reports"
if exist "target\jacoco.exec"      del /f /q   "target\jacoco.exec"
echo [INFO] Nettoyage terminé.

rem ============================================
rem ÉTAPE 2 : Build + Tests + Rapport JaCoCo
rem ============================================
echo.
echo [========================================]
echo [ ÉTAPE 2/3 : Build, Tests et JaCoCo ]
echo [========================================]
echo [INFO] Running mvn clean verify with JaCoCo...
call mvn -B -Pcoverage clean verify ^
    -Dmaven.test.failure.ignore=true ^
    -DskipTests=false

if %ERRORLEVEL% neq 0 (
    echo [ERROR] mvn verify failed. Check Maven logs for details.
    exit /b 1
)

rem --- Vérification critique : jacoco.exec doit exister ici ---
echo [INFO] Vérification de la génération de jacoco.exec...
if not exist "target\jacoco.exec" (
    echo [ERROR] jacoco.exec NOT generated by mvn verify.
    echo [ERROR] Possible causes:
    echo [ERROR]   - No tests were executed
    echo [ERROR]   - JaCoCo agent not injected properly ^(check surefire.argLine^)
    echo [ERROR]   - Forked JVM crashed before writing the exec file
    exit /b 1
)
echo [INFO] jacoco.exec found. Size:
dir "target\jacoco.exec" | findstr "jacoco.exec"

echo [INFO] Generating JaCoCo XML report...
call mvn -B jacoco:report ^
    -Djacoco.dataFile=target/jacoco.exec ^
    -DoutputDirectory=target/site/jacoco

if %ERRORLEVEL% neq 0 (
    echo [ERROR] Failed to generate JaCoCo report.
    exit /b 1
)

if not exist "target\site\jacoco\jacoco.xml" (
    echo [ERROR] jacoco.xml not found after jacoco:report.
    exit /b 1
)
echo [INFO] JaCoCo XML report ready: target\site\jacoco\jacoco.xml

rem ============================================
rem ÉTAPE 3 : Envoi à SonarCloud (une seule fois)
rem ============================================
echo.
echo [========================================]
echo [ ÉTAPE 3/3 : Envoi à SonarCloud ]
echo [========================================]
echo [INFO] Running SonarCloud analysis...

set "JACOCO_XML=target/site/jacoco/jacoco.xml"

rem Construire la commande SonarQube
set "SONAR_CMD=mvn -B sonar:sonar"
set "SONAR_CMD=!SONAR_CMD! -Dsonar.projectKey=%SONAR_PROJECT_KEY%"
set "SONAR_CMD=!SONAR_CMD! -Dsonar.organization=%SONAR_ORG%"
set "SONAR_CMD=!SONAR_CMD! -Dsonar.host.url=%SONAR_HOST%"
set "SONAR_CMD=!SONAR_CMD! -Dsonar.token=%SONAR_TOKEN%"
set "SONAR_CMD=!SONAR_CMD! -Dsonar.java.coveragePlugin=jacoco"
set "SONAR_CMD=!SONAR_CMD! -Dsonar.coverage.jacoco.xmlReportPaths=%JACOCO_XML%"
set "SONAR_CMD=!SONAR_CMD! -Dsonar.java.binaries=target/classes"
set "SONAR_CMD=!SONAR_CMD! -Dsonar.sources=src/main/java"
set "SONAR_CMD=!SONAR_CMD! -Dsonar.tests=src/test/java"
set "SONAR_CMD=!SONAR_CMD! -Dsonar.test.inclusions=src/test/**/*"
set "SONAR_CMD=!SONAR_CMD! -Dsonar.sourceEncoding=UTF-8"
set "SONAR_CMD=!SONAR_CMD! -Dsonar.java.source=17"
set "SONAR_CMD=!SONAR_CMD! -Dsonar.coverage.exclusions=**/model/**,**/dto/**,**/exception/**"
set "SONAR_CMD=!SONAR_CMD! -Dsonar.cpd.exclusions=**/model/**,**/dto/**"
set "SONAR_CMD=!SONAR_CMD! -Dsonar.scm.provider=git"

if exist "target\dependency" (
    set "SONAR_CMD=!SONAR_CMD! -Dsonar.java.libraries=target/dependency/*.jar"
)

echo [INFO] Commande SonarCloud: !SONAR_CMD!
call !SONAR_CMD!

if %ERRORLEVEL% neq 0 (
    echo [ERROR] SonarCloud analysis failed.
    exit /b 1
)

echo.
echo [========================================]
echo [ SUCCÈS : Analyse SonarCloud terminée  ]
echo [========================================]
echo [INFO] SonarCloud analysis completed successfully.
echo [INFO] Check your results at: https://sonarcloud.io/project/overview?id=%SONAR_PROJECT_KEY%
echo.
endlocal
